### ISSUE TITLE
Änderung die eigentlich Ersatztermin hat ohne Ersatztermin

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/Schnittstelle#10]
Es gibt Änderungen die eigentlich einen Ersatztermin haben aber in der Datenbank kein Ersatztermin steht wodurch sie als entfallen angesehen werden.

Vermutung:
Die Änderungen werden auf der Webseite als besonderst wichtig hervorgehoben (rot markiert) und deswegen anders gehandhabt.

Anhang:
Screenshot von der Datenbank, in der man sieht das Ersatzraum, Ersatzzeit und LV_ENTFALL_Stunden leer sind und ein Ersatzraum bei dem Feld "Text" steht.
![anderung entfallen statt verschoben](https://user-images.githubusercontent.com/19249397/31586610-9990ace2-b1d3-11e7-9b20-12ab3dd18496.png)

Frage:
Stimmt die Vermutung das es sich um wichtig hervorgehobene Änderungen handelt?
Stimmt der Ersatzraum im Feld "Text"? Und wie sieht es bei Verschiebungen die als wichtig hervorgehoben werden aus?
Und:
Soll die Schnittstelle nun das Feld "Text" mitschicken?

**Comment by GlaserDaniel** [comment]
Okay, so kann es auch aussehen:
![anderung stepping](https://user-images.githubusercontent.com/19249397/31928173-6566efce-b897-11e7-99bb-1c0497fdaf6c.PNG)

Also wird die Schnittstelle demnächst einfach das Feld Text mit geben und falls es gesetzt ist kann es in der App angezeigt werden. Soll das Feld Text wirklich als neues Feld "Text" hinzugefügt werden? Oder irgendwelche namens Wünsche? Oder soll es zum Beispiel zu bei "reason" mit gegeben werden?

**Comment by PeterRill** [comment]
Ich finde es ziemlich blöd, hier wieder einen eigentlich unnötigen Sonderfall abbilden zu müssen. Das wäre nicht nötig, wenn die Änderung korrekt ins System eingetragen werden würde.

Wie soll man so eine Änderung korrekt anzeigen? Bei der iOS-App werden die Termine in den Kalender eingetragen und Änderungen dabei berücksichtigt, d.h. der Termin entsprechend korrigiert. Mit solchen Daten geht das nicht. Bei mir ist es ähnlich, ich zeige auch die nächsten Vorlesungen an und berücksichtige dabei die Änderungen.

Wieso ignorieren wir diesen Unsinn nicht einfach? Sollen sich die Studenten doch bitte dort beschweren, wo die Änderungen falsch eingegeben werden.

Könnte ich den kompletten Datensatz (z.B. als CSV) für die beiden o.g. Beispiele bekommen, dann rede ich mal mit Frau Ried von der Stundenplanung über das Thema.

**Comment by GlaserDaniel** [comment]
Ja, das wäre die bessere Lösung. Aber das wird dauern. Und bis dahin wird es weil solche Änderungen geben und die Studenten verpassen sie dann. Deswegen wäre halt die Idee die Information einfach mal noch mit zu geben.

Die zwei Verlegungen als CSV:
[Verlegungen.zip](https://github.com/HochschuleHofStundenplanapp/Schnittstelle/files/1410157/Verlegungen.zip)

**Comment by GlaserDaniel** [comment]
Aktueller Stand: 
Der Stundenplanung wurde geschrieben und das Feld "Text" wird jetzt erst mal nicht mit gegeben.

**Comment by cpfeiffer94** [comment]
Fortführung in Issue #12
