### ISSUE TITLE
Erweiterung PHP Schnittstelle Stundenplanänderungen um Feld: text (Auf Webseite roter Text)

### ISSUE THREAD

**Issue by cpfeiffer94** [HochschuleHofStundenplanapp/Schnittstelle#12]
Auf der HS Webseite wird bei manchen Stundenplanänderungen ein roter Text angezeigt (Beispiel Wirtschaftrecht 1. Semester). Hier werden teilweise wichtige Informationen abgespeichert. Unsere Schnittstelle liefert diesen Text nicht.
Die Schnittstelle ist dahingehend zu erweitern, dass das Datenbankfeld text in dem JSON mitgeliefert wird.

**Comment by pstoehr** [comment]
Im JSON-Changes Objekt gibt es bereits ein Comment-Feld. Was steht denn da drin und falls es leer ist, wäre dass doch dafür prädestiniert

**Comment by cpfeiffer94** [comment]
Ursprünglich war es auch meine Vermutung, dass der rote Text, welcher auf der Webseite angezeigt wird in dem Feld Comment hinterlegt ist (welches wie bereits beschrieben in dem JSON-Changes Objekt bereits enthalten ist.) Bei näherer Betrachtung hat sich jedoch herausgestellt, dass in dem Comment Feld, dasselbe wie zu der Vorlesung in der Stundenplantabelle steht (Beispiel: MC5+MI5 oder "Vorlesung nur in Englischer Sprache").

Da in der SPLUS Software keine Vorlesungen eines Dozenten zur gleichen Zeit stattfinden dürfen, wurde wie in dem Beispiel Screenshot ersichtlich, der Ersatztermin in das Datenbankfeld Text geschrieben. Der Inhalt des Datenbankfeldes Text erscheint dann in roter Schrift auf der Hochschulseite, wird aber nicht von der Schnittstelle ausgeliefert. Deswegen muss als Voraussetzung dafür, dass wir diesen roten Text in den Stundenplanapps anzeigen können, das JSON-Changes Objekt dahingehen erweitert werden.

![image001](https://user-images.githubusercontent.com/22813839/32601264-53787712-c542-11e7-804f-6e1f8761057b.png)
(Bildquelle: Rechenzentrum HS Hof)

**Comment by cpfeiffer94** [comment]
Das Datenbankfeld "Text" wird jetzt in Schnittstellenversion 3.5 ausgeliefert.

Das iOS-Stundenplanteam wurde über diese Änderung informiert.
Die Androidapp wird von mir angepasst.

In den späteren Stored Procedure Update soll das Ganze dann auch so ausgegeben werden:

<img width="938" alt="bildschirmfoto 2017-11-13 um 16 39 31" src="https://user-images.githubusercontent.com/22813839/32734099-4922ae02-c891-11e7-8f66-b528a4d0f33d.png">
<img width="504" alt="bildschirmfoto 2017-11-13 um 16 16 04" src="https://user-images.githubusercontent.com/22813839/32733037-8f124560-c88e-11e7-8494-819a8ed1d5bb.png">
<img width="313" alt="bildschirmfoto 2017-11-13 um 17 22 47" src="https://user-images.githubusercontent.com/22813839/32737294-fed23238-c899-11e7-93ac-de2b372417af.png">


EDIT: im JSON Objekt steht das ganze unter "text" ;-)

https://app.hof-university.de/soap/client.php?f=Changes&stg=WR&sem=1a&tt=WS

**Comment by sirjofri** [comment]
@cpfeiffer3008 wäre es nicht sinnvoll, solche änderungen auf einem separaten branch zu machen, anstatt die komplette verzeichnisstruktur umzustellen und backup-ordner anzulegen? Dafür gibt es nämlich branches (und dafür verwendet man sie auch). Generell hast du schon recht, eine gute struktur braucht das repository, und die fehlt momentan noch etwas.

Mein vorschlag ist: wir überlegen uns eine gut organisierte verzeichnisstruktur (neues issue), stellen die vorhandenen punkte um und arbeiten mit branches (Ich habe mir diesbezüglich auch schon gedanken gemacht). Ein häufiges wechseln der verzeichnisse ist nämlich nicht gut zum arbeite und wird in der historie schnell unübersichtlich. Deine kleine änderung hat nämlich so gut wie alles geändert. Sollte man mal zurückrollen müssen, weil etwas nicht funktioniert, ergibt das ein gewaltiges chaos.

Falls es um die git-funktionalität geht kann ich auch gerne mal eine einführung in branches geben, falls gewünscht.

**Comment by cpfeiffer94** [comment]
Hallo @sirjofri ,
erstmal sry, dass ich mit meiner Verzeichnisumstellung die CLI-Fraktion mit Füßen getreten habe (Daran habe ich garnicht gedacht).

Ich finde es sollten immer die aktuellen PHP-Skripte von dem App Server in dem master Branch sein. Das Rechenzentrum hat anscheinend in den Semesterferien auch ein paar Dinge geändert. Falls es dir weiterhilft, könnte man zumindest die Struktur des Ordners mit dem PHP Skripten wieder auf die alte Struktur bringen... Dann funktionieren deine Kommandos auch wieder wie gewohnt ;-)

Ansonsten bin ich natürlich offen für deine Ideen und wir können sehr gerne in einem Issue Punkte zur Verbesserung sammeln und danach umsetzen :-)

Nachdem die Sache mit dem roten Text nun in der Schnittstelle umgesetzt ist werde ich diesen Issue nun schließen. Du kannst ja in deinem neuen Issue schreiben, ob dir das mit dem Zurücksetzen auf die alte Verzeichnisstruktur taugt.

Viele Grüße
Christian
