### ISSUE TITLE
Erweiterung der FCM Token Tabelle um Provider (für iOS)

### ISSUE THREAD

**Issue by cpfeiffer94** [HochschuleHofStundenplanapp/Schnittstelle#13]
Provider ist bisher nur für Google Firebase vorhanden und soll für Apple APNS erweitert werden.
Spaltenname: 
Neue Spalte: Provider
Werte : Android = 1 / iOS = 2

mit Johannes Franz und Normen Krug von dem iOS Team umsetzen.

**Comment by jofranz** [comment]
Die Vorgehensweise im Swift FWPM wurde hier noch nicht konkret festgelegt. Eine neue Idee der letzten Tage bringt den vorherigen Plan noch einmal durcheinander.
Ich liefere hier Infos sobald etwas mehr Klarheit herrscht.

**Comment by avinotec** [comment]
Die Spalte wurde soeben in der Produktiv und Testdatenbank ergänzt. Änderungen sind produktiv.
Android=0
iOS=1
