### ISSUE TITLE
Erweiterung der FCM-Token Tabelle um Sprache

### ISSUE THREAD

**Issue by GlaserDaniel** [HochschuleHofStundenplanapp/Schnittstelle#14]
Wenn jemand schon neue Spalten macht bei der FCM-Token Tabelle, dann auch gleich für die Sprache. 
Also Spaltenname language. 
Als Werte dann so was wie de_DE und en_EN. Dann wären später auch andere Sprachen möglich. Oder halt auch so einen Zahlencode mit deutsch = 1 und englisch = 2.
Weil die Push Notifications bisher nur auf deutsch sind.

**Comment by sirjofri** [comment]
Dann würde ich aber nicht gleich `de_DE` bzw `en_EN` machen, weil ich nicht glaube, dass wir bei den paar Daten mehrere deutsche bzw englische Einträge brauchen. Kann letztlich aber auch egal sein, weil was in dem Feld drinsteht, ist letztlich (aus technischer Sicht) recht egal.

**Comment by avinotec** [comment]
Die Tabelle ist soeben von Herrn Karl erweitert worden. Bitte in der API Dokumentation ergänzen. Bitte ebenso ergänzen, dass wir gemäß JAVA ISO Notation: de, en, ... verwenden wollen. Default-Wert ist "de"....

Ist schon eingespielt in Test und Produktion.
