### ISSUE TITLE
Vergangene Änderungen nicht mit übertragen

### ISSUE THREAD

**Issue by apoehlmann** [HochschuleHofStundenplanapp/Schnittstelle#2]

**Comment by lukasmahr** [comment]
Verstehe nicht ganz, was gemeint ist. Ein paar zusätzliche Infos wären schön. Danke!

**Comment by drui** [comment]
In der Schnittstelle die wir gerade verwenden werden auch Stundenplanänderungen geliefert die in der Vergangenheit liegen.  
Im Moment laden wir einfach alles und ignorieren alles was vor dem aktuellen Datum liegt.  
Wenn wir nur Daten bekommen die in der Zukunft liegen, würden wir weniger laden müssen. Vor allem bei mobilen Geräten gut.

**Comment by ghost** [comment]
Fixed
