### ISSUE TITLE
URLs für Schnittstellen

### ISSUE THREAD

**Issue by drui** [HochschuleHofStundenplanapp/Schnittstelle#5]
Bitte eine URL für jede Schnittstelle.  
https://www.hof-university.de/soap/client.php  + rest

Und das nächste mal bitte erst Dokumentieren und dann online stellen.

**Comment by lukasmahr** [comment]
Wie in den letzten Besprechungen abgesprochen, existiert hierfür im Testsystem eine docs.php. Dort sind alle Teile der Schnittstelle dokumentiert.

Und das nächste mal bitte erst bei Kollegen informieren oder selbst zur Besprechung kommen, bevor ein Issue erstellt wird.

**Comment by drui** [comment]
Auf das Testsystem kann man aber fast nicht zugreifen. 
Und solche Sachen sollten eigentlich für alle gut einsehbar öffentlich verfügbar sein.  

Wie sinnlos die Besprechungen sind zeigt das jemand der da war auch nichts davon wusste.  
Und das die neue Schnittstelle einfach heute mal Live gegangen ist. Darüber wurden wir auch nicht informiert.

**Comment by lukasmahr** [comment]
Die Dokumentation befindet sich direkt bei der Schnittstelle, also genau da, wo sie benötigt wird. Auf Wunsch des IT Services wird diese nur im Testsystem angezeigt.

Wie bereits geschrieben, wurde dies auch so besprochen. Diese Besprechungen, ohne selbst anwesend gewesen zu sein, als sinnlos zu betiteln, halte ich für sehr fragwürdig.

Zum Thema Update der Live-Schnittstelle: Dass dieses Update heute vorgenommen wurde, wussten wir auch nicht. Ich sehe aber kein Problem darin, da sich das komplette System ja noch in der Entwicklungsphase befindet.

**Comment by apoehlmann** [comment]
Die Dokumentation der Schnittstelle war im Gespräch, aber nie direkt wo es genau liegt und ob es wirklich kommt. Bitte eine Notiz ins Wiki und @avinotec  wir bräuchten mehr Koordination zwischen IT-Service und den App-Teams.

**Comment by drui** [comment]
Hier ist die Doku:
https://stundenplan-hshof.firebaseapp.com/
Aber die ist veraltet. (also die Version hier vom Git)

**Comment by ghost** [comment]
Kannst du bitte etwas genauer ausführen, was an dieser Version veraltet ist?
Ich habe die Version erstellt, nachdem entschieden worden ist, dass die Mensa nicht mehr integriert werden soll. Deshalb sollten die Angaben korrekt sein. 

Für die Zukunft, bitte spendiere deinen Issues und Comments ein paar mehr Wörter, denn wir hatten schon in anderen Situationen  das Problem, dass wir nicht konkret wussten was du genau möchtest.

**Comment by drui** [comment]
wenn ich es richtig gelesen habe ist das die version 1. auf dem livesystem ist aber die version 2.

und zu dem anderem. das war n isssuevon alex nichr von mir. ich hatte sonst nur mal nach beispielen für jsonstrings gefragt.

edit: grad nochmal geschaut. stimmt is aktuell. tut mir leid. habs nur überflogen und die überschrift gesehen.

**Comment by drui** [comment]
hierdas war das andere 
https://github.com/HochschuleHofStundenplanapp/Schnittstelle/issues/2
