### ISSUE TITLE
Stundenplanänderungen

### ISSUE THREAD

**Issue by drui** [HochschuleHofStundenplanapp/Schnittstelle#6]
https://www.hof-university.de/soap/client.php?f=Changes&stg=Inf&sem=6  
Man bekommt auf keine Anfrage antworten.

**Comment by lukasmahr** [comment]
Der Fehler ist für uns nicht nachvollziehbar, da wir keinen Zugriff auf diesen Server haben. Lokal besteht der Fehler nicht.

**Comment by drui** [comment]
Jetzt bekommen wir jede Änderung 3 mal. (wenn ich nicht irgendwo was übersehe und es unterschiedliche Änderungen sind).  
Auf jeden Fall besteht das Problem bei Informatik. Andere Studiengänge hab ich nicht getestet.
https://www.hof-university.de/soap/client.php?f=Changes&stg=Inf&sem=6&tt=SS
