### ISSUE TITLE
Neue Schnittstelle liefert keine Daten

### ISSUE THREAD

**Issue by apoehlmann** [HochschuleHofStundenplanapp/Schnittstelle#7]
https://www.hof-university.de/soap/client.php?f=Courses`

`
{
    "version": 3,
    "courses": []
}
`

Andere Schnittstellen liefern auch keinen Inhalt, aber es wurden nicht alle getestet

**Comment by apoehlmann** [comment]
Haben das Problem gelöst. Bitte so dokumentieren das man es findet

**Comment by apoehlmann** [comment]
Es wäre gut wenn die Auswahl von SS/WS optional wäre

**Comment by lukasmahr** [comment]
Wir haben das Flag für SS/WS beschlossen, damit es keinen "zusammengeworfenen" Stundenplan aus mehreren Semestern mehr gibt. Daher halte ich es schon für sinnvoll, diesen als Pflichtparameter zu behalten.

**Comment by drui** [comment]
Hat sich noch mehr geändert oder nur dieser (meiner Meinung nach auch besser optionaler) Parameter?

**Comment by ghost** [comment]
Nein es hat sich nichts weiteres geändert. Ich verstehe die Diskussion gerade nicht, warum soll der Parameter der in der letzten Besprechung als notwendig festgelegt wurde jetzt wieder optional werden.

Falls euch die Situation nicht ganz klar ist, versuche ich euch das mal kurz zu erläutern.
Wir gehen mal davon aus, dass wir das 2 Semester von BWL abfragen wollen. Jetzt haben wir jedoch das Problem, dass sowohl im 'SS' als auch im 'WS' dieses Semester angeboten wird. Wie soll ich nun ohne den neuen Parameter unterscheiden, welches der richtige Eintrag ist?

Nennt doch bitte mal einen Grund, warum der Parameter optional werden soll? Bis jetzt sagt ihr immer nur ihr fändet es besser, aber warum?

**Comment by drui** [comment]
Und nach ein bisschen testen hat sich gezeigt das sich doch noch was geändert hat.
"year": "2016" war vorher noch nicht drin.

Hier dann auch nochmal die neue öffentliche Doku: https://stundenplan-hshof.firebaseapp.com/

**Comment by apoehlmann** [comment]
Es ist schon verständlich wieso der Parameter da ist und das er wichtig ist für den Nutzer. Aber dadurch das diese Angabe optional ist können wir auch bei Bedarf aus beiden Semestern die Stundenpläne laden. Das würde die Schnittstelle flexibler machen, denn der Entwickler hat dann die Macht darüber  zu entscheiden was er macht und nicht die Schnittstelle.
Wenn Einträge doppelt sind, kann man immer noch zwischen SS/WS wählen.

**Comment by ghost** [comment]
Ja das hat sich auch noch geändert, da hast du recht, habe ich wohl vergessen.
Jedoch wurde auch das alles in der letzten Besprechung diskutiert, weshalb sich ein kommen lohnt.

Da ich keinen Grund sehe das an dieser Stelle zu diskutieren, wird das mein letzter Beitrag, denn genau für so etwas haben wir unsere Besprechungen. Da wurde der Parameter gewünscht und so ist das jetzt beschlossen. Ich habe mit der aktuellen Version keine Bauchschmerzen und empfinde es als gut. Ohne den Parameter müsste die ganze JSON-Struktur angepasst werden, da man eine Unterscheidung machen müsste, zu welchem Jahr und Semesterhalbjahr gehört den das dargestellte Semester. Das wäre in meinen Augen keine schlanke Schnittstelle mehr. Für den ungewöhnlichen Fall, dass ihr beide Semester wollt, macht doch einfach 2 getrennte Anfragen.

Wenn ihr doch noch bedenken/wünsche habt, solltet ihr das denk ich mal an Herrn Stepping heran tragen. Die Entscheidungsgewalt ob etwas gemacht wird liegt dann doch eher bei Ihm.

**Comment by drui** [comment]
Zu den Treffen hab ich aber nichr immer Zeit, wie ich schonmal geschrieben hatte.

Und ich hab die Änderung jetzt eingebaut. Vor einem bestimmten Datum wird die eine Adresse verwendet, sonst die andere. 

Und nach der Abgabe wird die App von uns wahrscheinlich sowieso nicht mehr weiter gepflegt. Code bleibt aber trotzdem privat.

**Comment by apoehlmann** [comment]
Ich weiß über was wir gesprochen haben. Mir geht es mehr darum das die Schnittstelle anders reagieren soll, denn ein leeres Array ist nicht gerade hilfreich. Eine Fehlermeldung wäre da sehr hilfreich, wenn schon der Parameter pflicht ist.

Wie zum Beispiel:
`
{ "version": 3, "error" = "Die Anfrage konnte nicht verarbeitet werden. Bitte SS/WS angeben", "courses": [] } 
`
