### ISSUE TITLE
Doppelte Vorlesungen

### ISSUE THREAD

**Issue by PaulForstner** [HochschuleHofStundenplanapp/Schnittstelle#8]
Für Wing IT Semester 6 Sommersemester gilt folgendes: 
Dienstags sind die Vorlesungen Produktentwicklung von 14 bis 15:30 und 15:45 bis 17:15 doppelt.
In der Weboberfläche werden diese durch zusätzliches zuweisen von Gruppen (AT) und (MB) unterschieden, diese Unterscheidung fehlt in der Schnittstelle.

**Comment by GlaserDaniel** [comment]
Es gibt nun die Information "sp" die für diese Gruppen die Information liefert.
